name: charset
description: Charset encoding and decoding Library, include iso-(2-15), windows series, shift-jis. And supportted charset detect, canEncode, canDecode.
version: 1.2.0
publish_to: 'none' # Prevent to publish to pub.dev

environment:
  sdk: ">=3.4.0 <4.0.0"

dev_dependencies:
  test:
  lints: ^4.0.0
